# Generated by Django 3.0.5 on 2020-06-09 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyer_gst_no', models.CharField(max_length=15)),
                ('eyer_hotel_name', models.CharField(max_length=15)),
                ('eyer_address_1', models.CharField(max_length=50)),
                ('eyer_address_2', models.CharField(max_length=50)),
                ('eyer_city', models.CharField(max_length=40)),
                ('eyer_state', models.CharField(max_length=40)),
                ('eyer_website', models.CharField(max_length=50)),
                ('eyer_type', models.CharField(max_length=20)),
                ('eyer_category', models.CharField(max_length=50)),
                ('eyer_cuisines', models.CharField(max_length=50)),
                ('eyer_no_seats', models.IntegerField(default=0)),
                ('eyer_active_job_post', models.IntegerField(default=0)),
                ('eyer_tot_no_job_post', models.IntegerField(default=0)),
                ('eyer_job_offer', models.IntegerField(default=0)),
                ('eyer_job_hier', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_no', models.CharField(max_length=10, unique=True)),
                ('user_email', models.EmailField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=15)),
                ('user_login_data_time', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(max_length=8)),
                ('user_otp', models.CharField(max_length=6)),
                ('user_section', models.IntegerField(default=0)),
                ('user_pay', models.BooleanField(default=False)),
                ('user_pay_expery', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyer_name', models.CharField(max_length=50)),
                ('eyer_location', models.CharField(max_length=50)),
                ('eyer_number', models.IntegerField(default=0)),
                ('job_post', models.CharField(max_length=50)),
                ('job_salary', models.CharField(max_length=30)),
                ('job_experience', models.CharField(max_length=20)),
                ('job_employment', models.CharField(max_length=20)),
                ('job_gender', models.CharField(max_length=15)),
                ('job_age', models.IntegerField(default=0)),
                ('job_education', models.CharField(max_length=20)),
                ('job_skills', models.CharField(max_length=50)),
                ('job_discription', models.TextField(max_length=300)),
                ('job_working_days', models.IntegerField(default=0)),
                ('job_working_shifts', models.CharField(max_length=30)),
                ('job_benefits', models.CharField(max_length=200)),
                ('job_posted_name', models.CharField(max_length=750)),
                ('job_posted_dasignation', models.CharField(max_length=50)),
                ('job_no_emplyee_appilied', models.IntegerField(default=0)),
                ('job_post_opened', models.IntegerField(default=0)),
                ('eyer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='eyer_id', to='database_app.EmployerDetails')),
            ],
        ),
        migrations.AddField(
            model_name='employerdetails',
            name='user_id',
            field=models.OneToOneField(limit_choices_to={'user_type': 'employer'}, on_delete=django.db.models.deletion.CASCADE, to='database_app.UserLogin'),
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyee_name', models.CharField(max_length=50)),
                ('eyee_aadhar_no', models.CharField(max_length=12)),
                ('eyee_age', models.CharField(max_length=2)),
                ('eyee_gender', models.CharField(max_length=15)),
                ('eyee_address_1', models.CharField(max_length=50)),
                ('eyee_address_2', models.CharField(max_length=60)),
                ('eyee_city', models.CharField(max_length=40)),
                ('eyee_state', models.CharField(max_length=40)),
                ('eyee_type_hotel', models.CharField(max_length=20)),
                ('eyee_education', models.CharField(max_length=250)),
                ('eyee_choice', models.CharField(max_length=20)),
                ('eyee_time', models.CharField(max_length=20)),
                ('eyee_pre_experience', models.CharField(max_length=20)),
                ('eyee_place_pre_experience', models.CharField(max_length=20)),
                ('eyee_add_skills', models.CharField(max_length=300)),
                ('eyee_salary_expected', models.CharField(max_length=20)),
                ('user_id', models.OneToOneField(limit_choices_to={'user_type': 'employee'}, on_delete=django.db.models.deletion.CASCADE, to='database_app.UserLogin')),
            ],
        ),
    ]
