# Generated by Django 3.0.5 on 2020-06-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='eyee_no_accept',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='eyee_no_appiled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='eyee_no_post_liked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='eyee_no_rejected',
            field=models.IntegerField(default=0),
        ),
    ]
