# Generated by Django 3.0.5 on 2020-06-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0006_auto_20200611_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_active',
            field=models.BooleanField(default=True),
        ),
    ]
