# Generated by Django 3.0.5 on 2020-06-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0007_jobpost_job_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortListed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_list_type', models.CharField(max_length=20)),
                ('short_list_type_id', models.CharField(max_length=20)),
                ('confirmed', models.BooleanField(default=False)),
                ('eyee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_app.EmployeeDetails')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_app.JobPost')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyer_name', models.CharField(max_length=50)),
                ('job_post', models.CharField(max_length=50)),
                ('eyee_name', models.CharField(max_length=50)),
                ('offer_letter', models.CharField(max_length=1000)),
                ('eyee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_app.EmployeeDetails')),
                ('eyer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_app.EmployerDetails')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_app.JobPost')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyee_name', models.CharField(max_length=50)),
                ('eyer_name', models.CharField(max_length=50)),
                ('job_post', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=300)),
                ('what_can_he_do', models.CharField(max_length=300)),
                ('quries', models.CharField(max_length=300)),
                ('eyee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_app.EmployeeDetails')),
                ('eyer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_app.EmployerDetails')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_app.JobPost')),
            ],
        ),
    ]
