# Generated by Django 3.0.5 on 2020-06-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0009_jobpost_job_no_emplyee_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='job_active',
            field=models.BooleanField(default=True),
        ),
    ]
