# Generated by Django 3.0.5 on 2020-06-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0011_jobapplied_job_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplied',
            name='short_listed',
            field=models.BooleanField(default=False),
        ),
    ]
