# Generated by Django 3.0.5 on 2020-06-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0012_jobapplied_short_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlisted',
            name='job_active',
            field=models.BooleanField(default=True),
        ),
    ]
