# Generated by Django 3.0.5 on 2020-06-18 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0013_shortlisted_job_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerDetailsFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyer_name', models.CharField(max_length=50)),
                ('eyee_name', models.CharField(max_length=50)),
                ('eyee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_app.EmployeeDetails')),
                ('eyer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_app.EmployerDetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetailsFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyee_name', models.CharField(max_length=50)),
                ('job_post', models.CharField(max_length=50)),
                ('eyee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_app.EmployeeDetails')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database_app.JobPost')),
            ],
        ),
    ]
