# Generated by Django 3.0.5 on 2020-06-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0014_employeedetailsfav_employerdetailsfav'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetailsfav',
            name='unliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employerdetailsfav',
            name='unliked',
            field=models.BooleanField(default=False),
        ),
    ]
