# Generated by Django 3.0.5 on 2020-06-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0017_employeedetails_eyee_no_offered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='eyee_no_rejected',
            new_name='eyee_no_shortlisted',
        ),
    ]
