# Generated by Django 3.0.5 on 2020-06-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0018_auto_20200622_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='short_listed',
            field=models.BooleanField(default=False),
        ),
    ]
