# Generated by Django 3.0.5 on 2020-06-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0020_auto_20200625_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='user_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='user_phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
