# Generated by Django 3.0.5 on 2020-06-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0021_auto_20200625_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerdetails',
            name='eyer_hotel_name',
            field=models.CharField(max_length=50),
        ),
    ]
