# Generated by Django 3.0.5 on 2020-06-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0022_auto_20200626_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerdetails',
            name='eyer_type',
            field=models.CharField(max_length=25),
        ),
    ]
