# Generated by Django 3.0.5 on 2020-07-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0023_auto_20200626_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_created=True)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
