# Generated by Django 3.0.5 on 2020-07-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0024_logindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindata',
            name='otp',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AlterField(
            model_name='logindata',
            name='data_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
